---
- name: Install Certbot Debian
  snap:
    name: certbot
    state: present
    classic: yes

- name: Certbot sertificate generate
  command: sudo certbot certonly --webroot -w /var/www/{{ inventory_hostname }} --keep-until-expiring -n --agree-tos -d {{ inventory_hostname }} -m {{ my_email }}

- name: Add nginx SSL conf
  template:
    src: ssl.conf.j2
    dest: "{{ site_available }}ssl_{{ inventory_hostname }}.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: reload nginx

- name: Add symlinks for SSL conf
  file:
   src: "{{ site_available }}ssl_{{ inventory_hostname }}.conf"
   dest: "{{ site_enabled }}ssl_{{ inventory_hostname }}.conf"
   state: link
   force: yes
  notify:
    - reload nginx

- name: Flush handlers
  meta: flush_handlers