---
- name: Install nginx Debian
  apt:
    name: "{{ nginx_inst }}"
    state: present
    update_cache: yes
  notify: Start nginx

- name: Remove default conf and html
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ to_remove }}"

- name: Flush handlers
  meta: flush_handlers

- name: Add nginx conf Debian
  vars:
    nginx_user: www-data
  template:
   src: nginx.conf.j2
   dest: /etc/nginx/nginx.conf
   owner: root
   group: root
   mode: 0644
   force: yes
  notify: reload nginx